name: yoso
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.10.0
  - pytorch==2.4.0
  - torchvision==0.19.0
  - xformers~=0.0.27
  - pytorch-cuda==12.4
  - cuda-toolkit==12.4
  - transformers
  - diffusers==0.30.2
  - numpy==1.26.4
  - peft
  - tqdm
  - huggingface_hub
  - wandb
  - datasets[vision]

