name: yoso
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python~=3.10.0
  - pytorch==2.4.1
  - torchvision==0.19.1
  - xformers~=0.0.28
  - pytorch-cuda==11.8
  - cuda-toolkit==11.8
  - transformers==4.44.2
  - diffusers==0.30.2
  - numpy==1.26.4
  - peft
  - tqdm
  - huggingface_hub
  - wandb
  - datasets[vision]

